// Mocks generated by Mockito 5.4.6 from annotations
// in moodify/test/core/providers/profile/purchase_provider_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i5;
import 'package:purchases_flutter/models/entitlement_infos_wrapper.dart' as _i2;
import 'package:purchases_flutter/models/store_transaction.dart' as _i4;
import 'package:purchases_flutter/object_wrappers.dart' as _i3;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeEntitlementInfos_0 extends _i1.SmartFake
    implements _i2.EntitlementInfos {
  _FakeEntitlementInfos_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeStoreProduct_1 extends _i1.SmartFake implements _i3.StoreProduct {
  _FakeStoreProduct_1(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakePresentedOfferingContext_2 extends _i1.SmartFake
    implements _i3.PresentedOfferingContext {
  _FakePresentedOfferingContext_2(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [CustomerInfo].
///
/// See the documentation for Mockito's code generation for more information.
class MockCustomerInfo extends _i1.Mock implements _i3.CustomerInfo {
  MockCustomerInfo() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.EntitlementInfos get entitlements =>
      (super.noSuchMethod(
            Invocation.getter(#entitlements),
            returnValue: _FakeEntitlementInfos_0(
              this,
              Invocation.getter(#entitlements),
            ),
          )
          as _i2.EntitlementInfos);

  @override
  Map<String, String?> get allPurchaseDates =>
      (super.noSuchMethod(
            Invocation.getter(#allPurchaseDates),
            returnValue: <String, String?>{},
          )
          as Map<String, String?>);

  @override
  List<String> get activeSubscriptions =>
      (super.noSuchMethod(
            Invocation.getter(#activeSubscriptions),
            returnValue: <String>[],
          )
          as List<String>);

  @override
  List<String> get allPurchasedProductIdentifiers =>
      (super.noSuchMethod(
            Invocation.getter(#allPurchasedProductIdentifiers),
            returnValue: <String>[],
          )
          as List<String>);

  @override
  List<_i4.StoreTransaction> get nonSubscriptionTransactions =>
      (super.noSuchMethod(
            Invocation.getter(#nonSubscriptionTransactions),
            returnValue: <_i4.StoreTransaction>[],
          )
          as List<_i4.StoreTransaction>);

  @override
  String get firstSeen =>
      (super.noSuchMethod(
            Invocation.getter(#firstSeen),
            returnValue: _i5.dummyValue<String>(
              this,
              Invocation.getter(#firstSeen),
            ),
          )
          as String);

  @override
  String get originalAppUserId =>
      (super.noSuchMethod(
            Invocation.getter(#originalAppUserId),
            returnValue: _i5.dummyValue<String>(
              this,
              Invocation.getter(#originalAppUserId),
            ),
          )
          as String);

  @override
  Map<String, String?> get allExpirationDates =>
      (super.noSuchMethod(
            Invocation.getter(#allExpirationDates),
            returnValue: <String, String?>{},
          )
          as Map<String, String?>);

  @override
  String get requestDate =>
      (super.noSuchMethod(
            Invocation.getter(#requestDate),
            returnValue: _i5.dummyValue<String>(
              this,
              Invocation.getter(#requestDate),
            ),
          )
          as String);

  @override
  List<Object?> get props =>
      (super.noSuchMethod(Invocation.getter(#props), returnValue: <Object?>[])
          as List<Object?>);
}

/// A class which mocks [Package].
///
/// See the documentation for Mockito's code generation for more information.
class MockPackage extends _i1.Mock implements _i3.Package {
  MockPackage() {
    _i1.throwOnMissingStub(this);
  }

  @override
  String get identifier =>
      (super.noSuchMethod(
            Invocation.getter(#identifier),
            returnValue: _i5.dummyValue<String>(
              this,
              Invocation.getter(#identifier),
            ),
          )
          as String);

  @override
  _i3.PackageType get packageType =>
      (super.noSuchMethod(
            Invocation.getter(#packageType),
            returnValue: _i3.PackageType.unknown,
          )
          as _i3.PackageType);

  @override
  _i3.StoreProduct get storeProduct =>
      (super.noSuchMethod(
            Invocation.getter(#storeProduct),
            returnValue: _FakeStoreProduct_1(
              this,
              Invocation.getter(#storeProduct),
            ),
          )
          as _i3.StoreProduct);

  @override
  _i3.PresentedOfferingContext get presentedOfferingContext =>
      (super.noSuchMethod(
            Invocation.getter(#presentedOfferingContext),
            returnValue: _FakePresentedOfferingContext_2(
              this,
              Invocation.getter(#presentedOfferingContext),
            ),
          )
          as _i3.PresentedOfferingContext);

  @override
  List<Object> get props =>
      (super.noSuchMethod(Invocation.getter(#props), returnValue: <Object>[])
          as List<Object>);
}

/// A class which mocks [StoreProduct].
///
/// See the documentation for Mockito's code generation for more information.
class MockStoreProduct extends _i1.Mock implements _i3.StoreProduct {
  MockStoreProduct() {
    _i1.throwOnMissingStub(this);
  }

  @override
  String get identifier =>
      (super.noSuchMethod(
            Invocation.getter(#identifier),
            returnValue: _i5.dummyValue<String>(
              this,
              Invocation.getter(#identifier),
            ),
          )
          as String);

  @override
  String get description =>
      (super.noSuchMethod(
            Invocation.getter(#description),
            returnValue: _i5.dummyValue<String>(
              this,
              Invocation.getter(#description),
            ),
          )
          as String);

  @override
  String get title =>
      (super.noSuchMethod(
            Invocation.getter(#title),
            returnValue: _i5.dummyValue<String>(
              this,
              Invocation.getter(#title),
            ),
          )
          as String);

  @override
  double get price =>
      (super.noSuchMethod(Invocation.getter(#price), returnValue: 0.0)
          as double);

  @override
  String get priceString =>
      (super.noSuchMethod(
            Invocation.getter(#priceString),
            returnValue: _i5.dummyValue<String>(
              this,
              Invocation.getter(#priceString),
            ),
          )
          as String);

  @override
  String get currencyCode =>
      (super.noSuchMethod(
            Invocation.getter(#currencyCode),
            returnValue: _i5.dummyValue<String>(
              this,
              Invocation.getter(#currencyCode),
            ),
          )
          as String);

  @override
  List<Object?> get props =>
      (super.noSuchMethod(Invocation.getter(#props), returnValue: <Object?>[])
          as List<Object?>);
}

/// A class which mocks [EntitlementInfos].
///
/// See the documentation for Mockito's code generation for more information.
class MockEntitlementInfos extends _i1.Mock implements _i2.EntitlementInfos {
  MockEntitlementInfos() {
    _i1.throwOnMissingStub(this);
  }

  @override
  Map<String, _i3.EntitlementInfo> get all =>
      (super.noSuchMethod(
            Invocation.getter(#all),
            returnValue: <String, _i3.EntitlementInfo>{},
          )
          as Map<String, _i3.EntitlementInfo>);

  @override
  Map<String, _i3.EntitlementInfo> get active =>
      (super.noSuchMethod(
            Invocation.getter(#active),
            returnValue: <String, _i3.EntitlementInfo>{},
          )
          as Map<String, _i3.EntitlementInfo>);

  @override
  _i3.VerificationResult get verification =>
      (super.noSuchMethod(
            Invocation.getter(#verification),
            returnValue: _i3.VerificationResult.notRequested,
          )
          as _i3.VerificationResult);

  @override
  List<Object?> get props =>
      (super.noSuchMethod(Invocation.getter(#props), returnValue: <Object?>[])
          as List<Object?>);
}

/// A class which mocks [EntitlementInfo].
///
/// See the documentation for Mockito's code generation for more information.
class MockEntitlementInfo extends _i1.Mock implements _i3.EntitlementInfo {
  MockEntitlementInfo() {
    _i1.throwOnMissingStub(this);
  }

  @override
  String get identifier =>
      (super.noSuchMethod(
            Invocation.getter(#identifier),
            returnValue: _i5.dummyValue<String>(
              this,
              Invocation.getter(#identifier),
            ),
          )
          as String);

  @override
  bool get isActive =>
      (super.noSuchMethod(Invocation.getter(#isActive), returnValue: false)
          as bool);

  @override
  bool get willRenew =>
      (super.noSuchMethod(Invocation.getter(#willRenew), returnValue: false)
          as bool);

  @override
  String get latestPurchaseDate =>
      (super.noSuchMethod(
            Invocation.getter(#latestPurchaseDate),
            returnValue: _i5.dummyValue<String>(
              this,
              Invocation.getter(#latestPurchaseDate),
            ),
          )
          as String);

  @override
  String get originalPurchaseDate =>
      (super.noSuchMethod(
            Invocation.getter(#originalPurchaseDate),
            returnValue: _i5.dummyValue<String>(
              this,
              Invocation.getter(#originalPurchaseDate),
            ),
          )
          as String);

  @override
  String get productIdentifier =>
      (super.noSuchMethod(
            Invocation.getter(#productIdentifier),
            returnValue: _i5.dummyValue<String>(
              this,
              Invocation.getter(#productIdentifier),
            ),
          )
          as String);

  @override
  bool get isSandbox =>
      (super.noSuchMethod(Invocation.getter(#isSandbox), returnValue: false)
          as bool);

  @override
  _i3.OwnershipType get ownershipType =>
      (super.noSuchMethod(
            Invocation.getter(#ownershipType),
            returnValue: _i3.OwnershipType.purchased,
          )
          as _i3.OwnershipType);

  @override
  _i3.Store get store =>
      (super.noSuchMethod(
            Invocation.getter(#store),
            returnValue: _i3.Store.appStore,
          )
          as _i3.Store);

  @override
  _i3.PeriodType get periodType =>
      (super.noSuchMethod(
            Invocation.getter(#periodType),
            returnValue: _i3.PeriodType.intro,
          )
          as _i3.PeriodType);

  @override
  _i3.VerificationResult get verification =>
      (super.noSuchMethod(
            Invocation.getter(#verification),
            returnValue: _i3.VerificationResult.notRequested,
          )
          as _i3.VerificationResult);

  @override
  List<Object?> get props =>
      (super.noSuchMethod(Invocation.getter(#props), returnValue: <Object?>[])
          as List<Object?>);
}
