// Mocks generated by Mockito 5.4.6 from annotations
// in moodify/test/feature/profile/mixin/saved_videos_mixin_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;
import 'dart:ui' as _i5;

import 'package:mockito/mockito.dart' as _i1;
import 'package:moodify/core/model/saved_video.dart' as _i3;
import 'package:moodify/core/providers/saved_videos/saved_videos_provider.dart'
    as _i2;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

/// A class which mocks [SavedVideosProvider].
///
/// See the documentation for Mockito's code generation for more information.
class MockSavedVideosProvider extends _i1.Mock
    implements _i2.SavedVideosProvider {
  MockSavedVideosProvider() {
    _i1.throwOnMissingStub(this);
  }

  @override
  List<_i3.SavedVideo> get savedVideos =>
      (super.noSuchMethod(
            Invocation.getter(#savedVideos),
            returnValue: <_i3.SavedVideo>[],
          )
          as List<_i3.SavedVideo>);

  @override
  bool get isLoading =>
      (super.noSuchMethod(Invocation.getter(#isLoading), returnValue: false)
          as bool);

  @override
  bool get isSyncing =>
      (super.noSuchMethod(Invocation.getter(#isSyncing), returnValue: false)
          as bool);

  @override
  bool get hasListeners =>
      (super.noSuchMethod(Invocation.getter(#hasListeners), returnValue: false)
          as bool);

  @override
  bool isVideoSaved(String? videoId) =>
      (super.noSuchMethod(
            Invocation.method(#isVideoSaved, [videoId]),
            returnValue: false,
          )
          as bool);

  @override
  _i4.Future<void> saveVideo(_i3.SavedVideo? video) =>
      (super.noSuchMethod(
            Invocation.method(#saveVideo, [video]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<void> removeVideo(String? videoId) =>
      (super.noSuchMethod(
            Invocation.method(#removeVideo, [videoId]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<void> clearAll() =>
      (super.noSuchMethod(
            Invocation.method(#clearAll, []),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  void addListener(_i5.VoidCallback? listener) => super.noSuchMethod(
    Invocation.method(#addListener, [listener]),
    returnValueForMissingStub: null,
  );

  @override
  void removeListener(_i5.VoidCallback? listener) => super.noSuchMethod(
    Invocation.method(#removeListener, [listener]),
    returnValueForMissingStub: null,
  );

  @override
  void dispose() => super.noSuchMethod(
    Invocation.method(#dispose, []),
    returnValueForMissingStub: null,
  );

  @override
  void notifyListeners() => super.noSuchMethod(
    Invocation.method(#notifyListeners, []),
    returnValueForMissingStub: null,
  );
}
