// Mocks generated by Mockito 5.4.6 from annotations
// in moodify/test/feature/settings/mixin/settings_mixin_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i5;
import 'dart:io' as _i6;
import 'dart:ui' as _i7;

import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i9;
import 'package:moodify/core/providers/auth/auth_provider.dart' as _i3;
import 'package:moodify/core/providers/profile/purchase_provider.dart' as _i8;
import 'package:moodify/product/enum/auth_status.dart' as _i4;
import 'package:purchases_flutter/purchases_flutter.dart' as _i2;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeStoreProduct_0 extends _i1.SmartFake implements _i2.StoreProduct {
  _FakeStoreProduct_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakePresentedOfferingContext_1 extends _i1.SmartFake
    implements _i2.PresentedOfferingContext {
  _FakePresentedOfferingContext_1(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [AuthProvider].
///
/// See the documentation for Mockito's code generation for more information.
class MockAuthProvider extends _i1.Mock implements _i3.AuthProvider {
  MockAuthProvider() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.AuthStatus get status =>
      (super.noSuchMethod(
            Invocation.getter(#status),
            returnValue: _i4.AuthStatus.initial,
          )
          as _i4.AuthStatus);

  @override
  bool get isGoogleLoading =>
      (super.noSuchMethod(
            Invocation.getter(#isGoogleLoading),
            returnValue: false,
          )
          as bool);

  @override
  bool get isFacebookLoading =>
      (super.noSuchMethod(
            Invocation.getter(#isFacebookLoading),
            returnValue: false,
          )
          as bool);

  @override
  bool get isEmailLoading =>
      (super.noSuchMethod(
            Invocation.getter(#isEmailLoading),
            returnValue: false,
          )
          as bool);

  @override
  bool get isAuthenticated =>
      (super.noSuchMethod(
            Invocation.getter(#isAuthenticated),
            returnValue: false,
          )
          as bool);

  @override
  bool get hasListeners =>
      (super.noSuchMethod(Invocation.getter(#hasListeners), returnValue: false)
          as bool);

  @override
  _i5.Future<bool> updateProfile({String? username, String? avatarUrl}) =>
      (super.noSuchMethod(
            Invocation.method(#updateProfile, [], {
              #username: username,
              #avatarUrl: avatarUrl,
            }),
            returnValue: _i5.Future<bool>.value(false),
          )
          as _i5.Future<bool>);

  @override
  _i5.Future<void> signInWithGoogle() =>
      (super.noSuchMethod(
            Invocation.method(#signInWithGoogle, []),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Future<void> signInWithFacebook() =>
      (super.noSuchMethod(
            Invocation.method(#signInWithFacebook, []),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Future<void> signUpWithEmail(String? email, String? password) =>
      (super.noSuchMethod(
            Invocation.method(#signUpWithEmail, [email, password]),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Future<void> signInWithEmail(String? email, String? password) =>
      (super.noSuchMethod(
            Invocation.method(#signInWithEmail, [email, password]),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Future<bool> changePassword(String? newPassword) =>
      (super.noSuchMethod(
            Invocation.method(#changePassword, [newPassword]),
            returnValue: _i5.Future<bool>.value(false),
          )
          as _i5.Future<bool>);

  @override
  _i5.Future<bool> deleteAccount() =>
      (super.noSuchMethod(
            Invocation.method(#deleteAccount, []),
            returnValue: _i5.Future<bool>.value(false),
          )
          as _i5.Future<bool>);

  @override
  _i5.Future<void> signOut() =>
      (super.noSuchMethod(
            Invocation.method(#signOut, []),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Future<bool> uploadAvatar(_i6.File? imageFile) =>
      (super.noSuchMethod(
            Invocation.method(#uploadAvatar, [imageFile]),
            returnValue: _i5.Future<bool>.value(false),
          )
          as _i5.Future<bool>);

  @override
  _i5.Future<bool> deleteAvatar() =>
      (super.noSuchMethod(
            Invocation.method(#deleteAvatar, []),
            returnValue: _i5.Future<bool>.value(false),
          )
          as _i5.Future<bool>);

  @override
  _i5.Future<void> refreshProfile() =>
      (super.noSuchMethod(
            Invocation.method(#refreshProfile, []),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  bool isEmailProvider() =>
      (super.noSuchMethod(
            Invocation.method(#isEmailProvider, []),
            returnValue: false,
          )
          as bool);

  @override
  bool isGoogleProvider() =>
      (super.noSuchMethod(
            Invocation.method(#isGoogleProvider, []),
            returnValue: false,
          )
          as bool);

  @override
  bool isFacebookProvider() =>
      (super.noSuchMethod(
            Invocation.method(#isFacebookProvider, []),
            returnValue: false,
          )
          as bool);

  @override
  void clearError() => super.noSuchMethod(
    Invocation.method(#clearError, []),
    returnValueForMissingStub: null,
  );

  @override
  void addListener(_i7.VoidCallback? listener) => super.noSuchMethod(
    Invocation.method(#addListener, [listener]),
    returnValueForMissingStub: null,
  );

  @override
  void removeListener(_i7.VoidCallback? listener) => super.noSuchMethod(
    Invocation.method(#removeListener, [listener]),
    returnValueForMissingStub: null,
  );

  @override
  void dispose() => super.noSuchMethod(
    Invocation.method(#dispose, []),
    returnValueForMissingStub: null,
  );

  @override
  void notifyListeners() => super.noSuchMethod(
    Invocation.method(#notifyListeners, []),
    returnValueForMissingStub: null,
  );
}

/// A class which mocks [PurchaseProvider].
///
/// See the documentation for Mockito's code generation for more information.
class MockPurchaseProvider extends _i1.Mock implements _i8.PurchaseProvider {
  MockPurchaseProvider() {
    _i1.throwOnMissingStub(this);
  }

  @override
  List<_i2.Package> get availablePackages =>
      (super.noSuchMethod(
            Invocation.getter(#availablePackages),
            returnValue: <_i2.Package>[],
          )
          as List<_i2.Package>);

  @override
  bool get isLoading =>
      (super.noSuchMethod(Invocation.getter(#isLoading), returnValue: false)
          as bool);

  @override
  bool get isPremium =>
      (super.noSuchMethod(Invocation.getter(#isPremium), returnValue: false)
          as bool);

  @override
  bool get hasListeners =>
      (super.noSuchMethod(Invocation.getter(#hasListeners), returnValue: false)
          as bool);

  @override
  _i5.Future<void> initialize() =>
      (super.noSuchMethod(
            Invocation.method(#initialize, []),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Future<void> refreshCustomerInfo() =>
      (super.noSuchMethod(
            Invocation.method(#refreshCustomerInfo, []),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Future<void> loadOfferings() =>
      (super.noSuchMethod(
            Invocation.method(#loadOfferings, []),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Future<bool> purchasePackage(_i2.Package? package) =>
      (super.noSuchMethod(
            Invocation.method(#purchasePackage, [package]),
            returnValue: _i5.Future<bool>.value(false),
          )
          as _i5.Future<bool>);

  @override
  _i5.Future<void> restorePurchases() =>
      (super.noSuchMethod(
            Invocation.method(#restorePurchases, []),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  void dispose() => super.noSuchMethod(
    Invocation.method(#dispose, []),
    returnValueForMissingStub: null,
  );

  @override
  void addListener(_i7.VoidCallback? listener) => super.noSuchMethod(
    Invocation.method(#addListener, [listener]),
    returnValueForMissingStub: null,
  );

  @override
  void removeListener(_i7.VoidCallback? listener) => super.noSuchMethod(
    Invocation.method(#removeListener, [listener]),
    returnValueForMissingStub: null,
  );

  @override
  void notifyListeners() => super.noSuchMethod(
    Invocation.method(#notifyListeners, []),
    returnValueForMissingStub: null,
  );
}

/// A class which mocks [Package].
///
/// See the documentation for Mockito's code generation for more information.
class MockPackage extends _i1.Mock implements _i2.Package {
  MockPackage() {
    _i1.throwOnMissingStub(this);
  }

  @override
  String get identifier =>
      (super.noSuchMethod(
            Invocation.getter(#identifier),
            returnValue: _i9.dummyValue<String>(
              this,
              Invocation.getter(#identifier),
            ),
          )
          as String);

  @override
  _i2.PackageType get packageType =>
      (super.noSuchMethod(
            Invocation.getter(#packageType),
            returnValue: _i2.PackageType.unknown,
          )
          as _i2.PackageType);

  @override
  _i2.StoreProduct get storeProduct =>
      (super.noSuchMethod(
            Invocation.getter(#storeProduct),
            returnValue: _FakeStoreProduct_0(
              this,
              Invocation.getter(#storeProduct),
            ),
          )
          as _i2.StoreProduct);

  @override
  _i2.PresentedOfferingContext get presentedOfferingContext =>
      (super.noSuchMethod(
            Invocation.getter(#presentedOfferingContext),
            returnValue: _FakePresentedOfferingContext_1(
              this,
              Invocation.getter(#presentedOfferingContext),
            ),
          )
          as _i2.PresentedOfferingContext);

  @override
  List<Object> get props =>
      (super.noSuchMethod(Invocation.getter(#props), returnValue: <Object>[])
          as List<Object>);
}
